### ISSUE TITLE
error when I run your scripts

### ISSUE THREAD

**Issue by simonchen007** [drewgarrido/pidish_slicer#1]
hello,

the system showing error when I run you scripts:
-------------------------------------
# python3 slicer.py -i /root/pidish_slicer-master/10x10.stl -o /root/pidish_slicer-master/ouput/ -m /root/pidish_slicer-master/mask.png 
Finding best location...
Traceback (most recent call last):
  File "slicer.py", line 315, in <module>
    sys.exit(main())
  File "slicer.py", line 136, in main
    bottom_image_data = get_slice_image_data(optimized_scene, 0.5, mask.width, mask.height)
  File "/usr/lib/python3/dist-packages/PIL/Image.py", line 608, in __getattr__
    raise AttributeError(name)
AttributeError: width
--------------------------------------
how can I fix that ?

thanks

**Comment by drewgarrido** [comment]
It looks like you may be using the Python 2.7's version of PIL instead of the version that comes with Pillow for Python 3.5. I would check your Python installation to ensure Python is using Pillow instead of an older version of PIL.

I have the script running on a Windows installation with Anaconda installed. It lists my versions as Python 3.5.2 and Pillow 4.0.0. Typically, I run this slicer script on my PC and then send the images to my 3d printer to print them. My 3d printer runs my pidish software, and is using Python 2.7.
