### ISSUE TITLE
proformance issue

### ISSUE THREAD

**Issue by novioleo** [drewgarrido/pidish_slicer#3]
There is a another issue.
the larger mask i use,the much more time to cost.i don't need mask my model~~
how to generate slice without mask?do you have any idea?

**Comment by drewgarrido** [comment]
I made the mask optional. However, this required me to have the output width and height be specified on the command line instead of the mask, since the mask was being used to specify the width and height implicitly.

If you don't use a mask, the slices will be centered in the image, and the search for the best spot will not be performed.

This also allowed me to finish some optimizations I had been working on years ago. You should find the final result quite a bit faster.

**Comment by novioleo** [comment]
thks for your work~
